# Imports

In [3]:
import pandas as pd
import numpy as np
import os

## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Read in data and make sure relevant columns are string/character 

- San Diego data: `naics_code` and `account_key`
- NAICS details data: `naics` 

Run code below; if pulling from github, pathname should be fine; if working elsewhere may need to edit path name at read in

In [4]:
# uncomment if u need to find your path: os.getcwd()
SD = sd_df = pd.read_csv("../public_data/sd_df.csv")
NA = naics_df = pd.read_csv("../public_data/naics_df.csv")

In [5]:
cols_sd_use = ["naics_code", "account_key"]
cols_naics_use = ["naics"]

sd_df[cols_sd_use] = sd_df[cols_sd_use].astype(str)
naics_df[cols_naics_use] = naics_df[cols_naics_use].astype(str)

sd_df.dtypes
naics_df.dtypes
sd_df.head()
naics_df.head()

account_key          object
dba_name             object
council_district     object
naics_code           object
naics_description    object
naics_nchar           int64
dtype: object

naics                object
naics_description    object
dtype: object

,account_key,dba_name,council_district,naics_code,naics_description,naics_nchar
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4

    naics                 naics_description
0  111140                     Wheat Farming
1  111160                      Rice Farming
2  111150                      Corn Farming
3  111110                   Soybean Farming
4  111120  Oilseed (except Soybean) Farming

## "Inner join"- retain only San Diego businesses with details on their NAICS code

- Use the `naics_code` column in the San Diego business data as the join key
- Use the `naics` column in the NAICS code details data as the join key

- Do an inner join of the San Diego data onto the NAICS code details using these join keys
- After the inner join, print some examples of San Diego businesses lost in the merge
- Use value_counts() on the `naics_nchar` column in the San Diego data to see why they might have gotten lost

In [16]:
inner_join = SD.merge(NA, left_on = 'naics_code', right_on = 'naics', how = 'inner' )
inner_join
lost = SD[~SD['naics_code'].isin(inner_join['naics_code'])]
lost
SD['naics_nchar'].value_counts()

,account_key,dba_name,council_district,naics_code,naics_description_x,naics_nchar,naics,naics_description_y
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
1,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
2,1982006408,MAX L. PERLATTI & ASSOCIATES LLP,cd_2,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
3,1984014611,RBTK LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
4,1985008871,CWGB&S CPAS,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
5,1998004615,DELSEN & COMPANY LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
6,2006000166,GUERRERO JIMENEZ DIAZ & COMPANY LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
7,2007000136,MOSS ADAMS LLP,cd_7,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
8,2008016718,BDO USA LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
9,2010013586,SWENSON ADVISORS LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
10,2013053990,MURRILL & GERBINO LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
11,2014027828,STEES WALKER COMPANY LLP,cd_5,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
12,2019023546,REIWA ACCOUNTING LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants
13,1995006738,PADRES L P,cd_3,711211,SPORTS TEAMS AND CLUBS,6,711211,Sports Teams and Clubs
14,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
15,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
16,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
17,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
18,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
19,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,All Other Miscellaneous Wood Product Manufactu...
20,2000001077,MASSEY WEHR AND COMPANY LLP,cd_1,541213,TAX PREPARATION SERVICES,6,541213,Tax Preparation Services
21,2014034430,ALVAREZ TAX & ACCOUNTING LLP,cd_6,541213,TAX PREPARATION SERVICES,6,541213,Tax Preparation Services
22,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,All Other Miscellaneous Store Retailers (excep...
23,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,All Other Miscellaneous Store Retailers (excep...
24,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,All Other Miscellaneous Store Retailers (excep...
25,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,All Other Miscellaneous Store Retailers (excep...
26,2004006421,ROBBINS GELLER RUDMAN & DOWD LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,All Other Legal Services
27,2005012737,SLATER & TRUXAW LLP,cd_1,541199,ALL OTHER LEGAL SERVICES,6,541199,All Other Legal Services
28,2006009239,CONNOR & CUNDEL LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,All Other Legal Services
29,2006010738,WENTHUR LAW GROUP LLP,cd_2,541199,ALL OTHER LEGAL SERVICES,6,541199,All Other Legal Services
30,2007022822,THE LOAN COMPANY OF SAN DIEGO,cd_3,522291,CONSUMER LENDING,6,522291,Consumer Lending
31,2009003243,ALTMAN INVESTMENT COMPANY LP,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,Nonresidential Property Managers
32,2010012365,LAPIZ PROPERTIES GROUP LTD,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,Nonresidential Property Managers
33,2009010415,THE SUMMIT AT POINT LOMA APARTMENTS,cd_2,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,Residential Property Managers
34,2013067165,ARIEL,cd_3,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,Residential Property Managers
35,2019015278,BEYER BOULEVARD APARTMENTS LP,cd_8,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,Residential Property Managers
36,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,Miscellaneous Financial Investment Activities
37,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,Miscellaneous Financial Investment Activities
38,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,Miscellaneous Financial Investment Activities
39,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,Miscellaneous Financial Investment Activities
40,2018023600,ALLIED UNIVERSAL SECURITY SERVICES,cd_5,561612,SECURITY GUARDS & PATROL SERVICES,6,561612,Security Guards and Patrol Services
41,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,All Other Miscellaneous Food Manufacturing
42,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,All Other Miscellaneous Food Manufacturing
43,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,All Other Miscellaneous Food Manufacturing
44,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,All Other Miscellaneous Food Manufacturing
45,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,All Other Miscellaneous Food Manufacturing
46,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,Offices of All Other Miscellaneous Health Prac...
47,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,Offices of All Other Miscellaneous Health Prac...
48,2021010826,STARDUST FLOAT SPA LP,cd_2,812199,OTHER PERSONAL CARE SERVICES,6,812199,Other Personal Care Services
49,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance
50,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance
51,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance

,account_key,dba_name,council_district,naics_code,naics_description,naics_nchar
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4
5,1979053082,GRIMM VRANJES GREER STEPHAN & BRIDGMAN LLP,cd_3,5411,LEGAL SERVICES,4
6,1981000840,BENINK & SLAVENS LLP,cd_7,5411,LEGAL SERVICES,4
...,...,...,...,...,...,...
347,2006015404,9625 TOWN CENTRE PARTNERS LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3
348,2007015303,WFP-GATEWAY LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3
349,2007015336,WFP-MIRAMAR LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3
350,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3
352,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3

naics_nchar
5    150
4     89
6     49
3     42
2     23
Name: count, dtype: int64

## "Left join"- retain all sd businesses even if naics code isn't in `naics_df`

- Using the same join keys as above, and treating the San Diego businesses as the left hand side data, left join the naics code details onto the San Diego businesses
- Use the `indicator` argument within merge to create an indicator, `naics_merge_status`, to help with later merge diagnostics and examine sample of ones that didn't merge
- Use the `suffixes` argument within merge to add `_sd` as the left suffix, `_census` as the right suffix
- Use `naics_merge_status` in the merged result to look at a sample of San Diego businesses that weren't matched with `naics_df`

In [27]:
left_join = SD.merge(NA, left_on = 'naics_code', right_on = 'naics', how = 'left', suffixes = ['_sd', '_census'], indicator = 'naics_merge_status')
left_join[left_join['naics_merge_status'] != 'both']

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,naics,naics_description_census,naics_merge_status
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,NaN,NaN,left_only
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,NaN,NaN,left_only
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,NaN,NaN,left_only
5,1979053082,GRIMM VRANJES GREER STEPHAN & BRIDGMAN LLP,cd_3,5411,LEGAL SERVICES,4,NaN,NaN,left_only
6,1981000840,BENINK & SLAVENS LLP,cd_7,5411,LEGAL SERVICES,4,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...
362,2006015404,9625 TOWN CENTRE PARTNERS LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,NaN,NaN,left_only
363,2007015303,WFP-GATEWAY LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,NaN,NaN,left_only
364,2007015336,WFP-MIRAMAR LP,cd_3,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,NaN,NaN,left_only
365,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,NaN,NaN,left_only
369,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,NaN,NaN,left_only

## Use group by and agg to see if there are differences in merge rates by area

- Using the left-joined dataframe created in previous step, create a boolean indicator, `is_lost`, that equals `True` if the merge indicator is equal to "left_only" (and is otherwise false)
- Find the proportion of businesses by council district that were lost in the left join (SD businesses that failed to match to `naics_df`). To do this, group by `council_district` and use the shortcut of taking the mean of the `is_lost` indicator to find the proportions lost by `council_district`.

In [23]:
left_join['is_lost'] = (left_join['naics_merge_status'] == "left_only")
left_join

left_join.groupby('council_district')['is_lost'].mean()

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,naics,naics_description_census,naics_merge_status,is_lost
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants,both,False
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,NaN,NaN,left_only,True
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,Offices of Certified Public Accountants,both,False
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,NaN,NaN,left_only,True
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,NaN,NaN,left_only,True
...,...,...,...,...,...,...,...,...,...,...
365,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,NaN,NaN,left_only,True
366,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance,both,False
367,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance,both,False
368,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,All Other Automotive Repair and Maintenance,both,False
369,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,NaN,NaN,left_only,True

council_district
cd_1    0.880597
cd_2    0.804348
cd_3    0.812500
cd_4    1.000000
cd_5    0.916667
cd_6    0.859649
cd_7    0.918919
cd_8    0.933333
cd_9    1.000000
Name: is_lost, dtype: float64

## Optional challenge exercise: add lagging 0's and see if merge rate improves

You noticed earlier that a big reason for non-matches is that the San Diego tax certificate NAICS codes were often less than six digits long, while the Census ones were always 6 digits.

You wonder if this is an issue where 0's in some of the SD's data naics codes got cut off (eg 540000 became 54), and if so whether adding these lagging zeros would improve the merge rate in a left join.

- Pad the `naics_code` column in `sd_df` with 0's to get that column up to 6-digits, using one of two approaches: 
  1. `str.pad` in pandas (https://pandas.pydata.org/docs/reference/api/pandas.Series.str.pad.html)
  2. for more of a challenge, write your own function! It should check the # of digits in the naics code string and pad it with 0's at the end up to 6 digits. To execute your function, use row-wise apply: `df.apply(lambda row: funcname(row.column), axis=1)`.
- Perform the same left join as above and see how the match rate changes
- Create an indicator variable--`is_new_match`---for new matches under the padded NAICS code; compare the `naics_description` column from San Diego versus Census in the new dataset for a sample of these new matches and comment on whether the padding seems to be correct

In [ ]:
# your code here